package SnakeGame;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import SnakeGame.View.Scene.MenuScene;
import SnakeGame.View.Scene.SceneManager;
import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.stage.Screen;
import javafx.stage.Stage;

/**
 * La classe principale de l'application Snake Game.
 * Responsable de l'initialisation et du démarrage de l'application.
 */
public class App extends Application {

    private static Rectangle2D screenBounds = Screen.getPrimary().getVisualBounds();
    private static final double screenWidth = screenBounds.getWidth();
    private static final double screenHeight = screenBounds.getHeight();

    /**
     * @return La largeur de l'écran.
     */
    public static double getScreenWidth() {
        return screenWidth;
    }

    /**
     * @return La hauteur de l'écran.
     */
    public static double getScreenHeight() {
        return screenHeight;
    }

    /**
     * @param stage Le stage principal de l'application.
     */
    @Override
    public void start(Stage stage) {
        SceneManager sceneManager = SceneManager.getInstance();
        sceneManager.setPrimaryStage(stage);
        sceneManager.changeScene(new MenuScene());
        sceneManager.show();
    }

    /**
     * La méthode principale pour lancer l'application.
     *
     * @param args Arguments du main.
     */
    public static void main(String[] args) {
        launch();
    }
}
